name: "Compile Flipper Application"

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout user application
        uses: actions/checkout@v4
        path: user_app

      - name: Checkout Flipper Zero Firmware
        uses: actions/checkout@v4
        with:
          repository: flipperdevices/flipperzero-firmware
          ref: release # Tu peux remplacer par 'dev' ou utiliser le repo d'un autre firmware (ex: RogueMaster/flipperzero-firmware-wip)
          path: flipper-firmware
          submodules: recursive

      - name: Copy app into firmware structure
        run: |
          mkdir -p flipper-firmware/applications_user/subghz_advanced
          cp -r user_app/* flipper-firmware/applications_user/subghz_advanced/

      - name: Set up Environment & Build FAP
        run: |
          cd flipper-firmware
          ./fbt fap_subghz_advanced

      - name: Upload Compiled FAP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: subghz_advanced_fap
          path: flipper-firmware/build/f7-firmware-*/apps/subghz_advanced.fap
